### ISSUE TITLE
cmus.el seems useful

### ISSUE THREAD

**Issue by FrancescElies** [kisom/personal.el#1]
Hi,

cmus.el seems useful, did you think to make a package out of it?

All best & thanks

**Comment by kisom** [comment]
I hadn't, I just stuck some code in my ~/.emacs.d... I actually don't know how to write emacs packages, so I'd have to learn how to do that.

**Comment by FrancescElies** [comment]
I have no experience either.
For the moment I copied your code to my emacs.d. If I ever come to put this into a package I'll write you back.

Thanks for your reply
